version: "3.9"
networks:
  reverse-proxy:
    driver: overlay
    external: true
volumes:
  steam:
  steamCMD:

services:
  palworld:
    image: cm2network/steamcmd:latest
    hostname: palworld
    user: steam
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.udp.routers.steamcmd.entrypoints=steamcmd"           # entrypoint->router
        - "traefik.udp.routers.steamcmd.service=steamcmd"               # router -> service
        - "traefik.udp.services.steamcmd.loadbalancer.server.port=8211" # port of service
    networks:
     - reverse-proxy
    volumes:
      - "steam:/home/steam/Steam"
      - "steamCMD:/home/steam/Steamcmd"
#     - "PalServer:/home/steam/Steam/steamapps/common/PalServer"
    #command: tail -f /dev/null
    #command: ./steamcmd +login anonymous +app_update 2394010 validate +quit
    #command: /home/steam/Steam/steamapps/common/PalServer/PalServer/PalServer.sh
